Rails.application.routes.draw do
  # this line was generated by 'rails_admin' gem
  mount RailsAdmin::Engine => '/backend', as: 'rails_admin'
  
  # rails 3 舊寫法
  # get '/', controller: 'pages', action: 'home'

  # get '/', to: 'pages#home'
  # 改將首頁設定為 candidates#index
  root 'candidates#index'
  resources :candidates do
    member do
      patch :vote
    end
  end

  resources :products

  # 較長的寫法（直接寫路徑）：
  # patch '/candidates/:id/vote', to: 'candidates#vote'
end
